/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2019-02-12 07:10:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class gps_005fjquery_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>Geolocation</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"initial-scale=1.0, user-scalable=no\">\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <style>\r\n");
      out.write("      /* Always set the map height explicitly to define the size of the div\r\n");
      out.write("       * element that contains the map. */\r\n");
      out.write("      #map {\r\n");
      out.write("        height: 100%;\r\n");
      out.write("      }\r\n");
      out.write("      /* Optional: Makes the sample page fill the window. */\r\n");
      out.write("      html, body {\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("      }\r\n");
      out.write("    </style>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <div id=\"map\"></div>\r\n");
      out.write("    <script>\r\n");
      out.write("      // Note: This example requires that you consent to location sharing when\r\n");
      out.write("      // prompted by your browser. If you see the error \"The Geolocation service\r\n");
      out.write("      // failed.\", it means you probably did not give permission for the browser to\r\n");
      out.write("      // locate you.\r\n");
      out.write("      var map, infoWindow;\r\n");
      out.write("      function initMap() {\r\n");
      out.write("        map = new google.maps.Map(document.getElementById('map'), {\r\n");
      out.write("          center: {lat: -34.397, lng: 150.644},\r\n");
      out.write("          zoom: 6\r\n");
      out.write("        });\r\n");
      out.write("        infoWindow = new google.maps.InfoWindow;\r\n");
      out.write("\r\n");
      out.write("        // Try HTML5 geolocation.\r\n");
      out.write("        if (navigator.geolocation) {\r\n");
      out.write("          navigator.geolocation.getCurrentPosition(function(position) {\r\n");
      out.write("            var pos = {\r\n");
      out.write("              lat: position.coords.latitude,\r\n");
      out.write("              lng: position.coords.longitude\r\n");
      out.write("            };\r\n");
      out.write("\r\n");
      out.write("            infoWindow.setPosition(pos);\r\n");
      out.write("            infoWindow.setContent('Location found.');\r\n");
      out.write("            infoWindow.open(map);\r\n");
      out.write("            map.setCenter(pos);\r\n");
      out.write("          }, function() {\r\n");
      out.write("            handleLocationError(true, infoWindow, map.getCenter());\r\n");
      out.write("          });\r\n");
      out.write("        } else {\r\n");
      out.write("          // Browser doesn't support Geolocation\r\n");
      out.write("          handleLocationError(false, infoWindow, map.getCenter());\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      function handleLocationError(browserHasGeolocation, infoWindow, pos) {\r\n");
      out.write("        infoWindow.setPosition(pos);\r\n");
      out.write("        infoWindow.setContent(browserHasGeolocation ?\r\n");
      out.write("                              'Error: The Geolocation service failed.' :\r\n");
      out.write("                              'Error: Your browser doesn\\'t support geolocation.');\r\n");
      out.write("        infoWindow.open(map);\r\n");
      out.write("      }\r\n");
      out.write("    </script>\r\n");
      out.write("    <script async defer\r\n");
      out.write("    src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyDcSiP_YUmvtf5SVuhe2gY4zsZ2OLb-QWQ&callback=initMap\">\r\n");
      out.write("    </script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
