/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2019-02-22 03:15:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class NewFile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=euc-kr\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js\"></script>\r\n");
      out.write("<title>A simple example</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.pannellum.org/2.3/pannellum.css\"/>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdn.pannellum.org/2.3/pannellum.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("    $(function() {        \r\n");
      out.write("        // Geolocation API에 액세스할 수 있는지를 확인\r\n");
      out.write("        if (navigator.geolocation) {\r\n");
      out.write("            //위치 정보를 얻기\r\n");
      out.write("            navigator.geolocation.getCurrentPosition (function(pos) {\r\n");
      out.write("                \r\n");
      out.write("            \t");
if(request.getParameter("lat")==null){
      out.write("\r\n");
      out.write("            \t$('#latitude').html(pos.coords.latitude);     // 위도\\\r\n");
      out.write("                $('#longitude').html(pos.coords.longitude); // 경도\r\n");
      out.write("  \r\n");
      out.write("                \r\n");
      out.write("               location.href=\"NewFile.jsp?lat=\"+pos.coords.latitude+\"&long=\"+pos.coords.longitude;\r\n");
      out.write("                ");
}
      out.write("\r\n");
      out.write("            });\r\n");
      out.write("        } else {\r\n");
      out.write("            alert(\"이 브라우저에서는 Geolocation이 지원되지 않습니다 chrome을 이용해주시기 바랍니다.\");\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("#panorama {\r\n");
      out.write("width: 600px;\r\n");
      out.write("height: 400px;\r\n");
      out.write("position: relative;\r\n");
      out.write("z-index: 1000;\r\n");
      out.write("display: table;\r\n");
      out.write("-moz-transform-origin: top left;\r\n");
      out.write("-webkit-transform-origin: top left;\r\n");
      out.write("-ms-transform-origin: top left;\r\n");
      out.write("transform-origin: top left;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script language = \"javascript\">\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function initScale(){\r\n");
      out.write("var ress = navigator.userAgent;\r\n");
      out.write("if (ress.indexOf(\"Android 1.\", 0) > -1 ){ //안드로이드2. 이하만 설정\r\n");
      out.write("if (ress.indexOf(\"480\", 0) > -1 ) { // 480x800\r\n");
      out.write("var per = 0.5226824457593688;\r\n");
      out.write("} else if(ress.indexOf(\"600\", 0) > -1 ) { // 600 x 1024\r\n");
      out.write("var per = 0.681\r\n");
      out.write("} else if(ress.indexOf(\"1280\", 0) > -1 ) { // 800 x 1280\r\n");
      out.write("var per = 0.631\r\n");
      out.write("}\r\n");
      out.write("} else {\r\n");
      out.write("var dh = window.innerHeight;\r\n");
      out.write("var dw = window.innerWidth;\r\n");
      out.write("var cw = parseInt( $('#panorama').css('width') );\r\n");
      out.write("var ch = parseInt( $('#panorama').css('height') );\r\n");
      out.write("var per = dw/cw;\r\n");
      out.write("var per2 =dh/ch;\r\n");
      out.write("if(per > per2 ){\r\n");
      out.write("per = per2;\r\n");
      out.write("}\r\n");
      out.write("var gapH = ( dh - (ch*per) )/2;\r\n");
      out.write("var gapW = ( dw - (cw*per) )/2\r\n");
      out.write("}\r\n");
      out.write("$(\"#panorama\").css('transform', 'scale('+per+','+per+')');\r\n");
      out.write("$('body').css('margin-top', gapH );\r\n");
      out.write("$('body').css('margin-left', gapW );\r\n");
      out.write("curScale = per;\r\n");
      out.write("}\r\n");
      out.write("window.onresize = function(){\r\n");
      out.write("initScale();\r\n");
      out.write("}\r\n");
      out.write("window.onload = function() {\r\n");
      out.write("initScale();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <!--Bootstrap core CSS-->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <!--Custom Fonts-->\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom styles for this template -->\r\n");
      out.write("    <link href=\"css/custom.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/contact-input-style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/hover-effect.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/font-awesome.min.css\" />\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div id=\"panorama\"></div>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("// 아래 코드의 01.jpg 만 원하는 이미지로 교체한 후 URL 을 적어주면 됩니다\r\n");
      out.write("\r\n");
      out.write("var sImageFileName = \"grand.jpg\";\r\n");
      out.write("pannellum.viewer('panorama', {\r\n");
      out.write("\"type\": \"equirectangular\",\r\n");
      out.write("\"panorama\": sImageFileName\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\t");

	String lati = request.getParameter("lat");
	String longi = request.getParameter("long");
	
	
      out.write("\r\n");
      out.write("<section class=\"banner-sec\">\r\n");
      out.write("<div class=\"jumbotron\">\r\n");
      out.write("<div class=\"container\"> \r\n");
      out.write("<br><br><br><br><br>\r\n");
      out.write("<h1>Search BOOK</h1>\r\n");
      out.write("<div class=\"input-group\">\r\n");
      out.write("<span class=\"input-group-btn\">\r\n");
      out.write("\t<form action=\"/team/search4\" method=\"get\">\r\n");
      out.write("\t<input type=\"text\" placeholder=\"책 검색\" class=\"form-control\" id=title name=booktitle>\r\n");
      out.write("\t<input type=\"hidden\" name=\"latitude\" value=");
      out.print(lati );
      out.write(">\r\n");
      out.write("\t<input type=\"hidden\" name=\"longitude\" value=");
      out.print(longi );
      out.write(">\r\n");
      out.write("\t<button type=\"submit\" class=\"btn btn-search\">Search</button>\r\n");
      out.write("\t</form>\r\n");
      out.write("</span>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section class=\"team-sec\" id=\"team\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <h2 class=\"text-center\">Our Team<br></h2>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col-lg-3 col-md-6 col-sm-6 text-center member-block\"> <img class=\"up-effect\" src=\"img/team-member-02.png\">\r\n");
      out.write("        <h3 class=\"up-effect\">김희영</h3>\r\n");
      out.write("        <div class=\"contact-con down-effect\"><i class=\"fa fa-phone fa-2x\"></i><i class=\"fa fa-envelope-o fa-2x\"></i><i class=\"fa fa-heart-o fa-2x\"></i></div>\r\n");
      out.write("              </div>\r\n");
      out.write("      <div class=\"col-lg-3 col-md-6 col-sm-6 text-center member-block\"> <img class=\"up-effect\" src=\"img/team-member-02.png\">\r\n");
      out.write("        <h3 class=\"up-effect\">윤효원</h3>\r\n");
      out.write("                <div class=\"contact-con down-effect\"><i class=\"fa fa-phone fa-2x\"></i><i class=\"fa fa-envelope-o fa-2x\"></i><i class=\"fa fa-heart-o fa-2x\"></i></div>                \r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-lg-3 col-md-6 col-sm-6 text-center member-block\"> <img class=\"up-effect\" src=\"img/team-member-01.png\">\r\n");
      out.write("        <h3 class=\"up-effect\">이윤지</h3>\r\n");
      out.write("        <div class=\"contact-con down-effect\"><i class=\"fa fa-phone fa-2x\"></i><i class=\"fa fa-envelope-o fa-2x\"></i><i class=\"fa fa-heart-o fa-2x\"></i></div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-lg-3 col-md-6 col-sm-6 text-center member-block\"> <img class=\"up-effect\" src=\"img/team-member-02.png\">\r\n");
      out.write("        <h3 class=\"up-effect\">차재현</h3>\r\n");
      out.write("                <div class=\"contact-con down-effect\"><i class=\"fa fa-phone fa-2x\"></i><i class=\"fa fa-envelope-o fa-2x\"></i><i class=\"fa fa-heart-o fa-2x\"></i></div>\r\n");
      out.write("      </div>\r\n");
      out.write("\t     </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<p class=\"text-center\">\r\n");
      out.write("\t\r\n");
      out.write("</p>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</footer>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core JavaScript\r\n");
      out.write("    ================================================== -->\r\n");
      out.write("    <!-- Placed at the end of the document so the pages load faster -->\r\n");
      out.write("    <script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->\r\n");
      out.write("    <script src=\"js/ie10-viewport-bug-workaround.js\"></script>\r\n");
      out.write("    <script src=\"js/oppear_1.1.2.min.js\"></script>\r\n");
      out.write("    <script> \r\n");
      out.write("\t\r\n");
      out.write("\t$(window).scroll(function () {\r\n");
      out.write("\t\tvar sticky = $('.navbar-brand'),\r\n");
      out.write("\t\t    scroll = $(window).scrollTop();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif (scroll >= 250) sticky.addClass('dark');\r\n");
      out.write("\t\t\telse sticky.removeClass('dark');\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$('.service-box').Oppear({\r\n");
      out.write("\t\tdelay : 500,\r\n");
      out.write("\t\t});\r\n");
      out.write("\t$('.main-text').Oppear({\r\n");
      out.write("\t\tdirection:'right',\r\n");
      out.write("\t});\r\n");
      out.write("\t$('.points').Oppear({\r\n");
      out.write("\t\tdirection:'left',\r\n");
      out.write("\t});\r\n");
      out.write("\t$('.up-effect').Oppear({\r\n");
      out.write("\t\tdirection:'up',\r\n");
      out.write("\t});\r\n");
      out.write("\t$('.down-effect').Oppear({\r\n");
      out.write("\t\tdirection:'down',\r\n");
      out.write("\t});\r\n");
      out.write("\t$('.left-effect').Oppear({\r\n");
      out.write("\t\tdirection:'right',\r\n");
      out.write("\t});\r\n");
      out.write("\t$('.right-effect').Oppear({\r\n");
      out.write("\t\tdirection:'left',\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("    </script>\r\n");
      out.write("    <script>\r\n");
      out.write("\t$('a[href^=\"#\"]').on('click', function(event) {\r\n");
      out.write("\r\n");
      out.write("    var target = $( $(this).attr('href') );\r\n");
      out.write("\r\n");
      out.write("    if( target.length ) {\r\n");
      out.write("        event.preventDefault();\r\n");
      out.write("        $('html, body').animate({\r\n");
      out.write("            scrollTop: target.offset().top\r\n");
      out.write("        }, 1000);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
