/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2019-02-19 02:24:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.PrintWriter;
import java.util.ArrayList;
import org.apache.catalina.startup.SetAllPropertiesRule;
import search.SearchServlet4;

public final class resultbook_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
 
//ArrayList<String[][]> list_book = new ArrayList<String[][]>();
/*    //request.getAttribute("list_book");
   ArrayList<String[][]> list_book = (ArrayList<String[][]>)request.getAttribute("list_book");
   System.out.println(list_book); */
   
   String [][] songpa =(String[][])request.getAttribute("songpa");
   String [][] seongbuk =(String[][])request.getAttribute("seongbuk");
   
   int arrayRows=(int)request.getAttribute("arrayRows");
   int arrayCols=(int)request.getAttribute("arrayCols");
   int arrayRows2=(int)request.getAttribute("arrayRows2");
   int arrayCols2=(int)request.getAttribute("arrayCols2");
   
  // System.out.println(songpa[0][0]);
  
 	ArrayList<String> title = new ArrayList<String>();
 	ArrayList<String> library = new ArrayList<String>();
 	
/*  	for (int i = 0; i < arrayCols; i++) {
        for (int j = 0; j < arrayRows; j++) {
        	out.print(songpa[j][i]+"&nbsp");
        	title.add(songpa[0][i]);
        }
        out.print("<br>");
 	} */

	for(int i=0;i<arrayCols;i++){
		title.add(songpa[0][i]);
		library.add(songpa[1][i]);
	}
	
 	
/*  	for (int i = 0; i < arrayCols2; i++) {
        for (int j = 0; j < arrayRows2; j++) {
        	out.print(seongbuk[j][i]+"&nbsp");
        	title.add(seongbuk[0][i]);
        }
        out.print("<br>");
     } */
	for(int i=0;i<arrayCols2;i++){
			title.add(seongbuk[0][i]);
			library.add(seongbuk[1][i]);
		} 	

 	for(int i=0;i<title.size();i++){
	 	out.print(title.get(i)+"&nbsp"+library.get(i));
	 	out.print("<br>");
 	}
 	
 	



      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
